export interface CourseStagePreset {
  stage_code: string;
  stage_name: string;
  theme: string;
  level: string;
  description: string;
  content: string;
  goal: string;
  sort_order: number;
  is_active: boolean;
}

export const DEFAULT_COURSE_STAGES: CourseStagePreset[] = [
  // Scratch 系列
  {
    stage_code: "scratch_beginner",
    stage_name: "Scratch初阶",
    theme: "Scratch",
    level: "beginner",
    description: "Scratch编程入门，学习基本概念和简单动画制作",
    content: "认识Scratch界面、角色与背景、运动与外观指令、事件与控制、简单的动画制作",
    goal: "能够独立完成简单的动画作品，理解编程的基本概念",
    sort_order: 1,
    is_active: true,
  },
  {
    stage_code: "scratch_intermediate",
    stage_name: "Scratch中阶",
    theme: "Scratch",
    level: "intermediate",
    description: "Scratch编程进阶，学习条件判断、循环和变量",
    content: "条件判断、循环结构、变量使用、侦测模块、声音控制、简单游戏制作",
    goal: "能够制作交互式游戏作品，掌握基本的程序逻辑",
    sort_order: 2,
    is_active: true,
  },
  {
    stage_code: "scratch_advanced",
    stage_name: "Scratch高阶",
    theme: "Scratch",
    level: "advanced",
    description: "Scratch编程高级，学习自定义积木和复杂项目",
    content: "自定义积木、列表与数据处理、克隆体、复杂游戏设计、项目优化",
    goal: "能够独立设计并完成复杂的项目作品",
    sort_order: 3,
    is_active: true,
  },
  // Python 系列
  {
    stage_code: "python_beginner",
    stage_name: "Python初阶",
    theme: "Python",
    level: "beginner",
    description: "Python编程入门，学习基础语法和数据类型",
    content: "Python环境搭建、基础语法、数据类型、输入输出、条件判断",
    goal: "掌握Python基本语法，能够编写简单的程序",
    sort_order: 4,
    is_active: true,
  },
  {
    stage_code: "python_intermediate",
    stage_name: "Python中阶",
    theme: "Python",
    level: "intermediate",
    description: "Python编程进阶，学习函数、模块和数据结构",
    content: "函数定义与调用、模块导入、列表与字典、文件操作、异常处理",
    goal: "能够编写结构化的Python程序，理解模块化编程思想",
    sort_order: 5,
    is_active: true,
  },
  {
    stage_code: "python_advanced",
    stage_name: "Python高阶",
    theme: "Python",
    level: "advanced",
    description: "Python编程高级，学习面向对象和项目实战",
    content: "面向对象编程、类与对象、继承与多态、常用库使用、项目实战",
    goal: "能够独立完成中等复杂度的Python项目",
    sort_order: 6,
    is_active: true,
  },
  // C++ 系列
  {
    stage_code: "cpp_beginner",
    stage_name: "C++基础语法",
    theme: "C++",
    level: "beginner",
    description: "C++编程入门，学习基础语法和程序结构，对标GESP1~2级知识点。",
    content: "变量、四则运算；scanf/printf格式化输入；判断语句；循环语句；数组",
    goal: "建立核心思维：理解「变量即容器」，掌握程序执行的「顺序、分支、循环」三大流程，会使用数组处理批量数据。",
    sort_order: 7,
    is_active: true,
  },
  {
    stage_code: "cpp_intermediate",
    stage_name: "C++进阶语法",
    theme: "C++",
    level: "intermediate",
    description: "C++语法编程进阶，在学会三大程序结构的基础上学会一些常用的工具，对标GESP3~5级知识点。",
    content: "字符、字符串；函数；结构体、指针与引用；STL容器、位运算与常用库函数；Sort排序",
    goal: "建立核心思维：学会「分而治之」（函数），「封装数据」（结构体），并懂得使用「强大的标准武器库」（STL）来高效解决问题。",
    sort_order: 8,
    is_active: true,
  },
  {
    stage_code: "cpp_advanced",
    stage_name: "C++基础算法",
    theme: "C++",
    level: "advanced",
    description: "C++基础算法和数据结构的学习，掌握基本的算法优化思想，对标GESP5~7级和CSP-J组知识点。",
    content: "排序算法；前缀和与差分；二分；双指针算法；高精度；位运算；链表与邻接表：树与图的存储；DFS与BFS；树与图的遍历、拓扑排序；筛质数、快速幂；背包问题；线性DP",
    goal: "建立核心思维：掌握「用空间换时间」、「化繁为简的递归与分治」、「最优子结构的动态规划」等核心算法思想。",
    sort_order: 9,
    is_active: true,
  },
  // 大颗粒系列
  {
    stage_code: "dk_beginner",
    stage_name: "小小乐高",
    theme: "大颗粒",
    level: "beginner",
    description: "本阶段是乐高启蒙课程，以生活场景与动物世界为核心，通过平面/立体互锁结构搭建，让幼儿认识日常物品、动物形态与生活规则，培养空间感知、动手能力与生活观察习惯，为后续机械与编程学习打基础。",
    content: "实验类型：生活场景搭建实验、动物形态模仿实验、空间规划实验；学科属性：学前启蒙（生活认知/语言表达）、工程学（基础互锁结构）、数学（形状/数字/空间认知）；核心知识点：平面互锁/转角互锁/阶梯互锁等基础搭建技巧；常见生活物品（电话、家具、交通工具）的结构认知；动物身体结构与形态特征；基础数字、形状、「里/外」「高/矮」等空间概念；生活礼仪与安全规则。",
    goal: "知识目标：认识20+种生活物品与动物形态，掌握3种以上基础互锁搭建方法，理解基础数字、形状与空间概念；能力目标：独立完成生活场景与动物模型搭建，能用语言描述作品结构与功能，具备基础空间规划与动手协调能力；成果目标：完成多款生活场景与动物作品，能遵守生活礼仪与安全规则，养成观察生活与爱护动物的习惯。",
    sort_order: 10,
    is_active: true,
  },
  {
    stage_code: "dk_intermediate",
    stage_name: "百变工程",
    theme: "大颗粒",
    level: "intermediate",
    description: "本阶段聚焦工程器械、成语故事与世界文化，通过机械臂、连接器与互锁结构搭建，让幼儿认识工程设备、传统文化与世界建筑，培养逻辑思维、动手创造与文化感知能力，衔接后续机械原理学习。",
    content: "实验类型：工程器械搭建实验、成语故事场景还原实验、文化建筑模仿实验；学科属性：学前启蒙（文化认知/语言表达）、工程学（机械臂/连接器应用）、数学（形状/对称/平衡认知）；核心知识点：机械臂、螺丝积木、连接器的灵活使用；外扩/内缩/单点阶梯等立体互锁结构；工程车辆（挖掘机、塔吊）的组成与功能；成语故事与传统节日的文化内涵；世界建筑、动物与科技设备的认知。",
    goal: "知识目标：认识20+种工程器械与文化载体，掌握机械臂与多种互锁结构搭建技巧，理解平衡、对称等基础逻辑；能力目标：独立完成复杂工程与文化场景搭建，能讲述成语故事与节日习俗，具备逻辑规划与动手创造能力；成果目标：完成多款工程模型与文化作品，能理解传统文化与世界知识，培养爱国情怀与科学探索精神。",
    sort_order: 11,
    is_active: true,
  },
  {
    stage_code: "dk_advanced",
    stage_name: "生活与科技",
    theme: "大颗粒",
    level: "advanced",
    description: "本阶段是机械启蒙核心课程，以生活中的机械装置为载体，让幼儿认识三角形稳定性、四边形灵活性、齿轮传动、杠杆、滑轮等基础机械原理，培养机械结构分析、问题解决与科学探究能力，为后续BricQ机械学习做铺垫。",
    content: "实验类型：机械结构搭建实验、传动原理验证实验、力学探究实验；学科属性：物理（力学/机械学基础）、工程学（机械结构设计）、数学（几何/平衡认知）；核心知识点：三角形稳定性、四边形灵活性；齿轮传动（加速/减速/冠齿）、蜗轮蜗杆、棘轮棘爪、连杆机构；杠杆（省力/费力）、滑轮、皮筋传动；生活机械（风扇、电梯、缝纫机）的工作原理。",
    goal: "知识目标：掌握5种以上基础机械原理，认识10+种生活机械的结构与功能，理解几何与力学基础逻辑；能力目标：独立完成复杂机械作品搭建，能分析机械传动路径与受力原理，具备问题拆解与调试能力；成果目标：完成多款生活机械作品，能解释作品机械原理与应用场景，培养科学探究与劳动意识。",
    sort_order: 12,
    is_active: true,
  },
  // 小颗粒系列
  {
    stage_code: "s9686_beginner",
    stage_name: "小颗粒机械基础",
    theme: "小颗粒",
    level: "beginner",
    description: "乐高9686小颗粒机械基础课程，从大颗粒过渡到小颗粒搭建",
    content: "小颗粒零件认知与操作技巧；梁、销、轴的连接方式；基础齿轮传动（直齿轮、锥齿轮）；杠杆原理与滑轮组；简单机械结构搭建（风扇、起重机、秤）",
    goal: "掌握小颗粒零件的基本连接方式，理解齿轮传动和杠杆原理，能独立搭建简单机械模型",
    sort_order: 13,
    is_active: true,
  },
  {
    stage_code: "s9686_intermediate",
    stage_name: "小颗粒机械进阶",
    theme: "小颗粒",
    level: "intermediate",
    description: "乐高9686小颗粒机械进阶课程，复合传动与复杂机械设计",
    content: "复合齿轮传动系统（多级变速）；蜗轮蜗杆机构应用；连杆机构与凸轮机构；气压与液压原理入门；复杂机械模型设计（挖掘机、机械臂、自动门）",
    goal: "掌握复合传动原理，能设计包含多种机械结构的复杂模型，理解能量转换与传递",
    sort_order: 14,
    is_active: true,
  },
  // BricQ 系列
  {
    stage_code: "bricq_beginner",
    stage_name: "BricQ趣动基础",
    theme: "BricQ",
    level: "beginner",
    description: "BricQ趣动基础课程，探索运动与力的基本原理",
    content: "推力与拉力；惯性运动与摩擦力；基础齿轮传动；杠杆原理与平衡；简单运动模型搭建（跷跷板、小车、陀螺）",
    goal: "理解力与运动的基本关系，掌握基础齿轮传动和杠杆原理，能搭建简单运动模型",
    sort_order: 15,
    is_active: true,
  },
  {
    stage_code: "bricq_intermediate",
    stage_name: "BricQ趣动进阶",
    theme: "BricQ",
    level: "intermediate",
    description: "BricQ趣动进阶课程，深入探索运动科学与能量转换",
    content: "能量转换（势能与动能）；弹性力与弹簧应用；复合传动系统；运动轨迹与速度控制；竞赛项目设计与优化（弹射器、赛车、投石机）",
    goal: "理解能量转换原理，能设计复合传动系统，完成竞赛类机械项目",
    sort_order: 16,
    is_active: true,
  },
  // WEDO2.0 系列
  {
    stage_code: "wedo_beginner",
    stage_name: "WeDo2.0初阶",
    theme: "WEDO2.0",
    level: "beginner",
    description: "WeDo2.0初阶课程，软硬件联动入门",
    content: "WeDo2.0硬件认知（马达、倾斜传感器、距离传感器）；图形化编程界面与基本指令；顺序结构与简单循环；单传感器触发控制；基础联动项目（风扇、扫地车、青蛙）",
    goal: "掌握WeDo2.0硬件连接，能编写含顺序和简单循环的图形化程序，实现单传感器触发控制",
    sort_order: 17,
    is_active: true,
  },
  {
    stage_code: "wedo_intermediate",
    stage_name: "WeDo2.0进阶",
    theme: "WEDO2.0",
    level: "intermediate",
    description: "WeDo2.0进阶课程，多传感器协同与复杂逻辑",
    content: "多传感器协同控制；条件判断与嵌套循环；马达速度与方向精确控制；消息传递与事件驱动；复杂联动项目（智能门禁、自动灌溉、迷宫小车）",
    goal: "掌握多传感器协同编程，能设计含条件判断和循环的复杂程序，独立完成综合性项目",
    sort_order: 18,
    is_active: true,
  },
  // SPIKE 系列
  {
    stage_code: "spike_beginner",
    stage_name: "SPIKE初阶",
    theme: "SPIKE",
    level: "beginner",
    description: "本阶段衔接WEDO2.0的机械搭建与图形化编程基础，以SPIKE软硬件为核心载体，聚焦梁结构机械搭建与基础图形化模块化编程（基于Scratch），完成从基础积木搭建到专业梁结构搭建、从简单编程到流程化编程的过渡，夯实软硬件基础联动能力，培养工程任务拆解与基础逻辑设计思维，为中阶复杂图形化编程做好铺垫。",
    content: "实验类型：SPIKE梁结构搭建实验、基础图形化编程实验、单传感器联动实验；学科属性：物理（机械传动/电子传感）、信息技术（Scratch图形化编程）、工程学；核心知识点：SPIKE梁结构搭建技巧，基础传动原理进阶应用；SPIKE核心硬件基础连接与单设备使用；基础图形化指令、单条件判断/基础循环及单传感器与电机联动。",
    goal: "知识目标：掌握SPIKE硬件基础功能及梁结构搭建逻辑，熟练运用基础图形化编程逻辑；能力目标：独立完成梁结构搭建，将流程图转化为图形化代码，实现单传感器与电机精准联动；成果目标：完成多款基础智能作品，实现简单避障、颜色识别触发等基础智能功能。",
    sort_order: 19,
    is_active: true,
  },
  {
    stage_code: "spike_intermediate",
    stage_name: "SPIKE中阶",
    theme: "SPIKE",
    level: "intermediate",
    description: "承接SPIKE初阶，聚焦复杂梁结构设计+高阶图形化编程，突破单设备控制局限，实现多传感器、多电机协同联动，培养系统思维与复杂工程问题拆解能力。",
    content: "实验类型：复杂梁结构组合搭建实验、高阶图形化编程实验、多传感器协同联动实验；学科属性：物理（多传动融合/传感高阶应用）、信息技术（图形化编程高阶）、工程学；核心知识点：SPIKE全器件组合搭建，多传动原理融合应用；SPIKE硬件多设备协同调试与端口分配；多条件判断、嵌套循环等高阶图形化逻辑，多硬件联动编程与程序优化。",
    goal: "知识目标：掌握SPIKE多器件协同原理，理解复杂图形化编程逻辑；能力目标：独立完成复杂梁结构搭建，编写含多条件判断、嵌套循环的图形化程序，实现多传感器多电机协同联动；成果目标：完成多款复杂智能作品，实现多传感器协同检测、多电机协调运动等高级功能。",
    sort_order: 20,
    is_active: true,
  },
  {
    stage_code: "spike_advanced",
    stage_name: "SPIKE高阶",
    theme: "SPIKE",
    level: "advanced",
    description: "从图形化编程全面过渡到纯Python代码编程，聚焦大型复杂工程模型设计+SPIKE专属Python编程，实现软硬件深度融合，培养代码思维、自主设计与工程问题创新解决能力。",
    content: "实验类型：大型工程模型搭建实验、SPIKE专属Python编程实验、软硬件深度联动调试实验、个性化项目设计实验；学科属性：物理（机械传感系统应用）、信息技术（Python编程）、工程学（大型系统设计）；核心知识点：大型模型架构设计与全维度优化；SPIKE全硬件全功能开发与协同控制；Python基础/进阶语法，SPIKE专属库应用，多设备协同的代码逻辑与个性化项目开发。",
    goal: "知识目标：精通SPIKE软硬件协同原理，掌握Python核心语法及SPIKE专属库用法，实现图形化逻辑到代码思维的转化；能力目标：独立完成定制化大型模型搭建优化，编写完整Python代码实现硬件精准控制，自主排查软硬件故障、解决工程问题；成果目标：完成多款大型定制化智能工程作品，实现全场景智能功能，能独立完成项目从需求分析到优化迭代的全流程。",
    sort_order: 21,
    is_active: true,
  },
];
